package com.mystudies.springboot2essentials.domain;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import javax.validation.constraints.NotEmpty;


@AllArgsConstructor
@NoArgsConstructor
@Data
@Builder
@Entity
public class Anime {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(description = "This is the anime's Id, generated by the Database", example = "3")
    private Long id;

    @NotEmpty(message = "The name cannot be empty nor null!")
    @Schema(description = "This is the anime's name", example = "YuYu Hakusho")
    private String name;
}
